### PR TITLE
just added shoukaku v3

### PR DESCRIPTION
**Pull request by TysonOP**

### CODE REVIEW

**Comment by hydrox19** [comment]
Is the PR tested?

**Comment by TysonOP** [comment]
> Is the PR tested?

Yes i tested it and it worked for me.. if your not working you should update your node cuz it gives null as search result sometimes..

**Review by hydrox19 — COMMENTED** [review]
Can you explain why are you using import statement?

**Comment by TysonOP** [comment]
> Can you explain why are you using import statement?

which one and where ?

**Review by hydrox19 — APPROVED** [review]

**Pull request merged**
